# Generated by Django 2.2.6 on 2019-10-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starwars', '0002_auto_20191014_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('course_code', models.CharField(max_length=10)),
                ('course_au', models.CharField(max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
